### ISSUE TITLE
Search by movie name

### ISSUE THREAD

**Issue by gschanuel** [alexanderwink/subdl#18]
When searching by filename in this case "Buster's Mal Heart (2017) BR-Rip AC3 6 [FGT].mkv" subdl finds no subtitle, but renaming the file to "Buster's Mal Heart" it does.

Maybe an option to download by movie name?

Thanks

**Comment by gabrielsimoes** [comment]
@alexanderwink, would you be interested in a PR for this? I'm really willing to write it.

**Comment by alexanderwink** [comment]
@gabrielsimoes Yes, much appreciated!
