### ISSUE TITLE
Glob problem in Linux

### ISSUE THREAD

**Issue by kugland** [alexanderwink/subdl#26]
I had problems downloading subtitles for a file containing '[' and ']' in the filename, because you are using the glob package on all arguments. I believe that at least on Unix-based operating systems you shouldn't apply glob to the arguments, since Unix shells already apply glob to the command lines.

Anyway, even on Windows it will fail when there are '[' or ']' on the filename.

**Comment by kugland** [comment]
This could be solved by conditionally applying `glob_arguments` only if `os.name != posix` in the function `parseargs`:

```python
if os.name != 'posix':
    arguments = glob_arguments(arguments)
```

This would also disable `glob` for Windows POSIX targets (like Cygwin), whose shells also already glob by default.

**Comment by alexanderwink** [comment]
I've removed the usage of glob
