### ISSUE TITLE
Support for post-processing (file encoding, file type)

### ISSUE THREAD

**Issue by mardab** [alexanderwink/subdl#28]
I have tried multiple other solutions and this is the best one at this moment. My only gripe is that for some languages default format is most often txt (which some players acknowledge, but never auto-load) with pre-utf8 encoding (which requires separate tool to correct it) and right now, unlike competitors, subdl has no built-in option to correct these problems.

Also, being able to check file encoding could also help with (automatic) subtitle selection, since newer, more likely to be better subtitles don't use anything else than unicode.

If possible, I'd like to contribute at least a preliminary support for post-processing, but before I do that I'd like to know how should I attempt it.

**Comment by milahu** [comment]
> check file encoding

[chardet](https://stackoverflow.com/questions/269060/is-there-a-python-library-function-which-attempts-to-guess-the-character-encodin)

> for some languages default format is most often txt

sounds like there are no timestamps in txt files?

converting txt to srt is non-trivial, this requires speech-recognition

probably low-quality offline speech-recognition (deepspeech or STT) will work
as you have both audio and text

similar https://github.com/abhirooptalasila/AutoSub

**Comment by RDKRACZ** [comment]
Without such basic feature as file encoding this tool is useless for any other subtitle language than English...
![image](https://user-images.githubusercontent.com/43277609/188318311-511ad9fa-efba-4d14-8a32-0a6f2967f2a4.png)

**Comment by milahu** [comment]
@RDKRACZ please test #29
