### ISSUE TITLE
argparse

### ISSUE THREAD

**Issue by milahu** [alexanderwink/subdl#30]
use [argparse](https://docs.python.org/3/library/argparse.html) to parse arguments

currently, we must set options first

```
subdl --option movie.mkv
```

but this should work too

```
subdl movie.mkv --option
```

**Comment by FranciscoRomao** [comment]
Hi, I am new to contributing to open source software, but I can help. Could I work on this feature? I guess I should work on it and then do a pull request to be eventually merged by the owner of the repo. Is that it?

**Comment by milahu** [comment]
just do it ; )

**Comment by FranciscoRomao** [comment]
Done.
